### ISSUE TITLE
Not working with ElementaryOS Juno 5.0

### ISSUE THREAD

**Issue by umbynos** [nightsense/elementary-panel-logomark#2]
![image](https://user-images.githubusercontent.com/34278123/57370023-66c59e80-718f-11e9-9b78-7a6dfbff45b0.png)
This is the result after following the instructions..

**Comment by nightsense** [comment]
Thanks for reporting @umbynos. I'm just going to archive this repo since it was designed for Loki, and Juno comes with a nice icon by the "Applications" text by default.
